// Generated by scripts/build-product-docs.mjs from product-docs/. Do not edit by hand.
import type { ProductDocSource } from "./types";

export const PRODUCT_DOC_SOURCES = [
  {
    slug: "visao-geral",
    title: "Visão geral",
    description: "O que é o Vanda Studio, quem são a Vanda e o Caetano, e onde fica cada coisa.",
    order: 10,
    keywords: "vanda caetano produto app aplicativo telas inicio comecar overview",
    markdown:
      "# Visão geral\n\nO Vanda Studio cuida do Instagram de pequenos negócios: observa o mercado, cria posts fiéis à marca e agenda ou publica quando o dono pede.\n\n## Vanda e Caetano\n\n- **Vanda** trabalha na **Conversa** do aplicativo. Cada negócio tem suas próprias conversas.\n- **Caetano** atende pelo **WhatsApp** do dono, com acesso a todos os negócios dele. Veja [Caetano no WhatsApp](/docs/caetano-no-whatsapp).\n\nOs dois usam as mesmas ferramentas: criar imagens e posts, pesquisar o mercado, agendar, ler e mudar configurações.\n\n## Telas do aplicativo\n\n- **Conversa**: onde se pede trabalho à Vanda.\n- **Galeria**: imagens geradas e enviadas do negócio.\n- **Calendário**: posts em rascunho, agendados, publicados ou com falha.\n- **Perfil**: plano e uso, modelos, conexões, marca, memória e skills.\n\n## Vários negócios\n\nUm dono pode ter vários negócios. Em **Barra lateral › seletor de negócio** você troca o negócio ativo, e **Adicionar negócio** cria um novo. Marca, memória, galeria e posts são separados por negócio; plano e cota são do dono.",
  },
  {
    slug: "conversa-e-criacao",
    title: "Conversa e criação",
    description: "Como pedir trabalho, anexar imagens e onde aparece o que foi criado.",
    order: 20,
    keywords:
      "conversa chat pedir criar imagem imagens anexar anexo foto arte carrossel infinito continuo panoramico loop story formato proporcao galeria encontrar trabalho resultado onde",
    markdown:
      '# Conversa e criação\n\n## Pedir trabalho\n\nDescreva o que quer na Conversa ("crie um carrossel sobre a promoção de sexta"). A Vanda executa até o fim sem pedir licença a cada passo e responde dizendo o que fez e onde está.\n\n## Imagens\n\n- A Vanda gera cada imagem completa, incluindo texto e layout, seguindo a identidade visual da marca.\n- Imagens anexadas na conversa já pertencem ao negócio e podem ser usadas direto, inclusive para editar ("troque o fundo desta foto").\n- Para usar o rosto do dono, um produto ou um lugar, envie a foto ou deixe-a nas referências da marca.\n\n## Tipos de post\n\n- **Imagem**: uma arte só, lida numa olhada.\n- **Carrossel**: de 2 a 10 slides, para passos, listas e comparações. Os slides mantêm a mesma paleta, tipografia e assinatura.\n- **Carrossel infinito**: de 3 a 5 slides que formam uma cena contínua, com elementos atravessando os cortes e o último slide voltando ao primeiro. Tem mais impacto visual e menos texto que o carrossel comum. Peça por "carrossel infinito", "contínuo" ou "panorâmico".\n- **Story**: 9:16. Fica como rascunho para você publicar pelo Instagram.\n\nA Vanda escolhe a proporção (1:1, 4:5, 3:4, 16:9 ou 9:16) pelo conteúdo e explica por quê. Todas as imagens de um post têm a mesma proporção. Fotos prontas que você enviou mantêm a proporção original quando o feed do Instagram a aceita (de 4:5 a 1,91:1, como 3:2 ou 5:4), sem serem repintadas.\n\nEnquanto monta um carrossel infinito, a Vanda salva versões intermediárias dos slides na Galeria. As versões substituídas saem sozinhas cerca de uma hora depois, a menos que algum post use a imagem.\n\n## Onde encontrar o resultado\n\nA conversa mostra as imagens e posts recém-criados. Depois:\n\n- **Galeria** guarda as imagens.\n- **Calendário** mostra os posts e o estado de cada um.\n\nPara rever algo de antes, peça à Vanda para mostrar de novo.',
  },
  {
    slug: "posts-e-agendamento",
    title: "Posts, agendamento e publicação",
    description: "Rascunhos, agendar, reagendar, cancelar e publicar, e o que fica no Calendário.",
    order: 30,
    keywords:
      "post posts rascunho criar agendar reagendar publicar publicacao cancelar apagar calendario story stories proposito justificativa falha draft schedule publish",
    markdown:
      '# Posts, agendamento e publicação\n\n## Rascunho primeiro\n\nPedir para criar um post produz um **rascunho**: não publica nem agenda. Uma data no pedido ("post para amanhã") ou a aprovação da arte não autorizam agendar.\n\nCada rascunho guarda o tipo (imagem, carrossel ou story), a proporção, o propósito (por exemplo anúncio, educacional ou prova social) e uma justificativa curta. A Vanda diz em uma frase por que escolheu cada um.\n\n## Agendar e publicar\n\n- Agendar, reagendar ou publicar exige um pedido explícito ("agende para sexta às 18h", "publique agora").\n- O fuso é sempre o horário de Brasília.\n- Reagendar muda a data do mesmo post; não cria outro.\n- Cancelar um agendamento devolve o post a rascunho.\n- Rascunhos e agendados podem ser apagados. Posts publicados não podem ser apagados nem editados por aqui.\n- **Stories** ainda não são publicados pela Vanda: o rascunho fica no Calendário para você publicar pelo Instagram.\n\n## Acompanhar\n\nO **Calendário** mostra cada post como rascunho, agendado, publicado ou com falha. Um agendado cujas imagens foram apagadas da Galeria falha com esse motivo em vez de ficar parado. Quando um agendamento publica ou falha, a conversa em que o post foi criado recebe um aviso; com o WhatsApp vinculado, o Caetano avisa por lá também.\n\nPublicar exige o Instagram do negócio conectado. Veja [Conexões](/docs/conexoes).',
  },
  {
    slug: "caetano-no-whatsapp",
    title: "Caetano no WhatsApp",
    description: "Vincular o WhatsApp, o que dá para enviar e receber, e como parar um pedido.",
    order: 40,
    keywords:
      "whatsapp caetano conectar vincular vinculo desconectar audio foto mensagem parar aviso notificacao",
    markdown:
      '# Caetano no WhatsApp\n\nO Caetano é o assistente do Vanda Studio no WhatsApp. Ele trabalha em todos os negócios do dono e usa as mesmas ferramentas da Vanda.\n\n## Vincular\n\n1. Abra **Perfil › Conexões › Caetano no WhatsApp**.\n2. Gere o vínculo e envie a mensagem pronta pelo seu WhatsApp. O link expira em 10 minutos; não compartilhe.\n3. Depois de vinculado, o mesmo cartão abre a conversa e permite desconectar.\n\n## O que dá para fazer\n\n- Enviar texto, fotos e áudios. Fotos chegam como anexos do negócio ativo; áudios são transcritos.\n- Receber imagens e posts prontos na própria conversa, com a legenda do post.\n- Receber avisos quando um post agendado é publicado ou falha.\n\nO Caetano cuida do marketing dos seus negócios e de dúvidas sobre o Vanda Studio. Pedidos fora disso ele recusa com educação.\n\n## Parar e reenviar\n\n- Envie "parar" para interromper o pedido em andamento e limpar a fila. Ações já concluídas, como publicações, não são desfeitas.\n- O cartão no Perfil mostra o estado das últimas entregas. Antes de reenviar uma resposta, confira se ela já não chegou.\n\n## Janela de 24 horas\n\nO WhatsApp só permite responder livremente até 24 horas depois da sua última mensagem. Fora disso, respostas esperam você escrever de novo; avisos de publicação podem chegar por uma mensagem modelo aprovada.',
  },
  {
    slug: "marca-e-memoria",
    title: "Marca e memória",
    description:
      "Fatos da marca, identidade visual e preferências que a Vanda e o Caetano guardam.",
    order: 50,
    keywords:
      "marca memoria preferencia preferencias identidade visual cor cores fonte fontes tagline kit referencias brand memory",
    markdown:
      '# Marca e memória\n\n## Marca\n\nEm **Perfil › negócio › Marca** ficam:\n\n- **Memória de marca**: fatos confirmados do negócio (produtos, preços, público). A Vanda não inventa fatos fora dela.\n- **Anotações da Vanda**: observações que ela registra durante o trabalho.\n- **Identidade visual**: cores exatas, fontes e tagline, usadas nas artes.\n\nPara corrigir cores, fontes ou tagline, diga na conversa; a Vanda atualiza a identidade visual.\n\n## Memória\n\nEm **Perfil › negócio › Memória** ficam as preferências duráveis ("nunca use vermelho", "sempre assine com o nome da loja"). Diga a preferência na conversa e ela é gravada. Confira a confirmação da gravação na resposta.\n\n## Skills\n\nEm **Perfil › negócio › Skills** ficam as habilidades especializadas instaladas, como produção de carrosséis e pesquisa de mercado no Instagram. São usadas automaticamente quando o pedido combina.',
  },
  {
    slug: "planos-e-uso",
    title: "Planos e uso",
    description: "Planos, cota de uso compartilhada, renovação e como mudar de plano.",
    order: 60,
    keywords:
      "plano planos uso cota limite renovacao assinatura cobranca pagamento teste gratis porcentagem chatgpt basico profissional",
    markdown:
      '# Planos e uso\n\n## Onde ver\n\nEm **Perfil › Plano e uso**: o plano atual, a porcentagem da cota usada, a renovação e mudanças de plano agendadas. A tela não mostra custo interno em dinheiro.\n\n## Como a cota funciona\n\n- O **teste grátis** tem uma cota única.\n- Planos pagos têm uma cota por período, compartilhada entre todos os negócios do dono.\n- Quando a cota acaba, novos pedidos ficam bloqueados até a renovação ou uma mudança de plano.\n\n## Planos\n\n- **Básico** e **Profissional**, mensais ou anuais.\n- **ChatGPT**: usa a assinatura do ChatGPT do dono para conversas e imagens enquanto a conta OpenAI está conectada. Sem a conexão, conversas e imagens usam o saldo do plano e param quando ele acaba; **Perfil › Plano e uso** mostra o aviso "Conta OpenAI desconectada" com o botão para conectar de novo. Veja [Conexões](/docs/conexoes).\n\n## Mudar de plano\n\nSó o dono muda de plano ou paga, em **Perfil › Plano e uso**. A Vanda e o Caetano podem dizer o plano e o uso atuais, mas não alteram a assinatura.',
  },
  {
    slug: "modelos",
    title: "Modelos",
    description:
      "Os modelos de conversa da Vanda e do Caetano e o modelo de imagem, e como trocar.",
    order: 70,
    keywords:
      "modelo modelos vanda caetano imagem imagens trocar mudar padrao gpt claude chatgpt openai",
    markdown:
      '# Modelos\n\nHá três escolhas independentes em **Perfil › Modelos**:\n\n- **Modelo da Vanda**: quem pensa nas conversas do aplicativo.\n- **Modelo do Caetano**: quem pensa no WhatsApp.\n- **Modelo de imagem**: quem gera e edita as imagens.\n\nA troca vale a partir da próxima mensagem. A lista completa de opções está em [Configurações](/docs/configuracoes).\n\n## Pedir a troca na conversa\n\nTambém dá para pedir à Vanda ou ao Caetano: "use o GPT-6.1 Sol como seu modelo". Eles mudam pelo mesmo caminho do Perfil e dizem qual era o anterior, para desfazer se quiser.\n\n## Plano ChatGPT\n\nNo plano ChatGPT com a conta OpenAI conectada, só aparecem os modelos que rodam pela assinatura. Uma escolha salva antes que não seja compatível passa a usar o modelo padrão.',
  },
  {
    slug: "conexoes",
    title: "Conexões",
    description: "Conectar o Instagram do negócio, a conta OpenAI do plano ChatGPT e o WhatsApp.",
    order: 80,
    keywords:
      "conexao conexoes conectar reconectar instagram publicar openai chatgpt assinatura whatsapp token",
    markdown:
      "# Conexões\n\n## Instagram\n\nCada negócio conecta o próprio Instagram em **Perfil › negócio › Conexões**. A conexão permite publicar e ler métricas privadas. Se uma publicação falhar por conexão expirada, conecte de novo.\n\n## Conta OpenAI\n\nNo plano ChatGPT, conecte sua assinatura em **Perfil › Conexões › Conta OpenAI**, com o código exibido. Ela só é usada enquanto o plano ChatGPT estiver ativo.\n\n## WhatsApp\n\nO vínculo com o Caetano fica em **Perfil › Conexões › Caetano no WhatsApp**. Veja [Caetano no WhatsApp](/docs/caetano-no-whatsapp).\n\nUma conexão registrada não garante que a credencial continue válida. A Vanda e o Caetano podem consultar o estado das conexões, mas conectar é sempre feito pelo dono.",
  },
] satisfies readonly ProductDocSource[];
