/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ErrorPreviewRouteImport } from './routes/error-preview'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as LoginSplatRouteImport } from './routes/login.$'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as DashboardPerfilRouteImport } from './routes/_dashboard.perfil'
import { Route as DashboardGaleriaRouteImport } from './routes/_dashboard.galeria'
import { Route as DashboardConversaRouteImport } from './routes/_dashboard.conversa'
import { Route as DashboardCalendarioRouteImport } from './routes/_dashboard.calendario'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorPreviewRoute = ErrorPreviewRouteImport.update({
  id: '/error-preview',
  path: '/error-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const LoginSplatRoute = LoginSplatRouteImport.update({
  id: '/login/$',
  path: '/login/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardPerfilRoute = DashboardPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGaleriaRoute = DashboardGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConversaRoute = DashboardConversaRouteImport.update({
  id: '/conversa',
  path: '/conversa',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarioRoute = DashboardCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/error-preview': typeof ErrorPreviewRoute
  '/onboarding': typeof OnboardingRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/calendario': typeof DashboardCalendarioRoute
  '/conversa': typeof DashboardConversaRoute
  '/galeria': typeof DashboardGaleriaRoute
  '/perfil': typeof DashboardPerfilRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/login/$': typeof LoginSplatRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/error-preview': typeof ErrorPreviewRoute
  '/onboarding': typeof OnboardingRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/calendario': typeof DashboardCalendarioRoute
  '/conversa': typeof DashboardConversaRoute
  '/galeria': typeof DashboardGaleriaRoute
  '/perfil': typeof DashboardPerfilRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/login/$': typeof LoginSplatRoute
  '/': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/error-preview': typeof ErrorPreviewRoute
  '/onboarding': typeof OnboardingRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/_dashboard/calendario': typeof DashboardCalendarioRoute
  '/_dashboard/conversa': typeof DashboardConversaRoute
  '/_dashboard/galeria': typeof DashboardGaleriaRoute
  '/_dashboard/perfil': typeof DashboardPerfilRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/login/$': typeof LoginSplatRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/error-preview'
    | '/onboarding'
    | '/sso-callback'
    | '/calendario'
    | '/conversa'
    | '/galeria'
    | '/perfil'
    | '/docs/$slug'
    | '/login/$'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error-preview'
    | '/onboarding'
    | '/sso-callback'
    | '/calendario'
    | '/conversa'
    | '/galeria'
    | '/perfil'
    | '/docs/$slug'
    | '/login/$'
    | '/'
    | '/docs'
  id:
    | '__root__'
    | '/_dashboard'
    | '/docs'
    | '/error-preview'
    | '/onboarding'
    | '/sso-callback'
    | '/_dashboard/calendario'
    | '/_dashboard/conversa'
    | '/_dashboard/galeria'
    | '/_dashboard/perfil'
    | '/docs/$slug'
    | '/login/$'
    | '/_dashboard/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  ErrorPreviewRoute: typeof ErrorPreviewRoute
  OnboardingRoute: typeof OnboardingRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  LoginSplatRoute: typeof LoginSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-preview': {
      id: '/error-preview'
      path: '/error-preview'
      fullPath: '/error-preview'
      preLoaderRoute: typeof ErrorPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/login/$': {
      id: '/login/$'
      path: '/login/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof LoginSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_dashboard/perfil': {
      id: '/_dashboard/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof DashboardPerfilRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/galeria': {
      id: '/_dashboard/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof DashboardGaleriaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/conversa': {
      id: '/_dashboard/conversa'
      path: '/conversa'
      fullPath: '/conversa'
      preLoaderRoute: typeof DashboardConversaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/calendario': {
      id: '/_dashboard/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof DashboardCalendarioRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCalendarioRoute: typeof DashboardCalendarioRoute
  DashboardConversaRoute: typeof DashboardConversaRoute
  DashboardGaleriaRoute: typeof DashboardGaleriaRoute
  DashboardPerfilRoute: typeof DashboardPerfilRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCalendarioRoute: DashboardCalendarioRoute,
  DashboardConversaRoute: DashboardConversaRoute,
  DashboardGaleriaRoute: DashboardGaleriaRoute,
  DashboardPerfilRoute: DashboardPerfilRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  ErrorPreviewRoute: ErrorPreviewRoute,
  OnboardingRoute: OnboardingRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  LoginSplatRoute: LoginSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
